georgringer/news

- .travis.yml
- Tests/Unit/ViewHelpers/SimplePrevNextViewHelperTest.php
- composer.json
Improve the test suite by testing more versions
> [TASK] Improve test suite

- Documentation/Settings.yml
Fixes https://github.com/georgringer/news/issues/148
> [BUGFIX] Update Settings.yml to newest version/release

- Documentation/DeveloperManual/ExtendNews/ExtendFlexforms/Index.rst
This is just a simple hook-reference update.
> [TASK] Update hook reference

- Documentation/AdministratorManual/Templates/ViewHelpers/LinkViewHelper.rst
the example shows how to add an additional parameter to an url.
> [TASK] add example to link viewhelper

- Configuration/TCA/Overrides/sys_file_reference.php
It eases the possibility to extend the newsPalette
> [TASK] Changes how showinpreview is added to palette,

- Resources/Private/Templates/News/List.xml
see http://www.w3schools.com/xml/rss_tag_enclosure.asp for details
> [TASK] add enclosure tag to deliver images in the stream

- Documentation/DeveloperManual/ExtendNews/ImportService/Index.rst
> [DOCU] Change Vendor in code example

- Classes/ViewHelpers/ExcludeDisplayedNewsViewHelper.php
- Classes/ViewHelpers/HeaderDataViewHelper.php
- Classes/ViewHelpers/IfIsActiveViewHelper.php
- Classes/ViewHelpers/ImageSizeViewHelper.php
- Classes/ViewHelpers/IncludeFileViewHelper.php
- Classes/ViewHelpers/LinkViewHelper.php
- Tests/Unit/ViewHelpers/ExcludeDisplayedNewsViewHelperTest.php
Refactors:
* ExcudeDisplayedNewsViewHelper
* HeaderDataViewHelper
* IfIsActiveViewHelper
* ImageSizeViewHelper
* IncludeFileViewHelper
* LinkViewHelper
> [TASK] Make ViewHelpers compilable, part 2

- Documentation/Tutorials/Templates/RenderContentElements/Index.rst
> [BUGFIX] Closing the content element 

- Build/.php_cs
- composer.json
> [TASK] Update php-cs-fixer to version 2.0

- Resources/Private/Templates/News/Month.html
eventnews must provide TypoScript to add a path to templateRootPaths
Resolves: #233
> [TASK] Remove symlink to eventnews template

- .gitattributes
- .gitlab-ci.yml
See https://gitlab.com/t3easy/news/pipelines/6274529 for an example
> [FEATURE] Add gitlab-ci configuration

- Classes/Backend/FormDataProvider/NewsFlexFormManipulation.php
Fix `\GeorgRinger\News\Backend\FormDataProvider\
...NewsFlexFormManipulation::addCategoryConstraints`
* correct array path
* add return statement
> [BUGFIX] Fix flexform category restriction FormDataProvider

- Classes/ViewHelpers/Social/GooglePlusViewHelper.php
> Added missing namespace

- Classes/Domain/Service/NewsImportService.php
This PR resolves:
* https://github.com/georgringer/news/issues/302 and
* https://github.com/georgringer/news/issues/301
> Import service fix

- .gitlab-ci.yml
- Use nimut/testing-framework as in travis
- Group similar jobs
https://docs.gitlab.com/ee/ci/pipelines.html#grouping-similar-jobs-in-the-pipeline-graph
- Use latest composer docker image
> [TASK] Update tests on GitLab ci

- Documentation/AdministratorManual/BestPractice/IntegrationWithTypoScript/Index.rst
Example: show category menu with typoscript
> example: Show Category Menu with Typoscript

- ext_emconf.php
> [TASK] Fix emconf issues

- Classes/Controller/NewsController.php
> [TASK] Fix typo in NewsController

- Resources/Private/Templates/Administration/Index.html
Display the ID and title on hover for the hovered category like "id: title"
> [TASK] Add a title attribute to the label

- Classes/Controller/NewsController.php
> [TASK] Fix small typo in news controller

- composer.json
> [BUGFIX] Fix composer autoloading for legacy classnames

- Classes/Controller/NewsController.php
- Classes/ViewHelpers/SimplePrevNextViewHelper.php
> SimplePrevNextViewHelper with custom sortField doesn't work

- Classes/Domain/Model/News.php
Changing the PhpDoc for getter and setter of property tsstamp.
> [TASK] Changing PhpDoc type for tsstamp

- Classes/Domain/Model/Dto/NewsDemand.php
- Tests/Unit/Domain/Model/Dto/NewsDemandTest.php
> Change datatype for tag in newsDemand to string

- Resources/Private/Templates/News/List.xml
The template should not output invalid feed syntax to have a wider range of supporting feed readers and so better accessibility
Feed validation can be done with : http://validator.w3.org/feed/
Please have a look on my changes and compare the output before and after my changes thx.
> Validated output for List.xml

- Classes/Backend/FormDataProvider/NewsFlexFormManipulation.php
Simply allow the fields in flexform to get limit + offset for tags
> #494 allow limit and offset for tags

- Resources/Private/Templates/Styles/Twb/Templates/ViewHelpers/Widget/Paginate/IndexAjax.html
See Issue https://github.com/georgringer/news/issues/599
> [BUGFIX] not generating data-link argument for Ajax Pagination (#599)

- Resources/Private/Templates/Administration/Index.html
> Remove useless zzz chars

- Classes/Hooks/ItemsProcFunc.php
Fixes grammar and adds an empty line.
> [FIX] Fixes a small grammar issue.

- Classes/Domain/Model/News.php
> [BUGFIX] Replace usage of deprecated method create_function()

- Classes/Hooks/RealUrlAutoConfiguration.php
- Documentation/AdministratorManual/BestPractice/Realurl/Index.rst
- Documentation/Misc/Changelog/7-0-0.rst
- composer.json
- ext_emconf.php
Also declare realurl as a suggestion to ensure it is loaded
before news is loaded.
> [TASK] Use up to date realurl configuration

- Classes/Controller/NewsController.php
When list action is called, it means no action argument
for detail was set, which happens when using skipControllerAndAction
setting.
We then check for news argument and forward to detail action.
> [BUGFIX] Forward from list to single when needed

- Configuration/TypoScript/setup.txt
With a height of 159 the video has a 16:9 ratio.
> Change ratio of video in detail view

- Documentation/AdministratorManual/BestPractice/Realurl/Index.rst
Making it a bit easier to understand where the config has to be.
> [DOC] Clarify where to set config for hrDates

- Documentation/DeveloperManual/ExtendNews/HooksSignals/Index.rst
Adds a fitting description for the example and changes the code to be more relatable.
> [DOC] Fix example for NewsControllerSettings hook

- Resources/Private/Templates/Styles/Twb/Templates/News/Detail.html
#760 fix for TWB styled detail view
>  Render related links as link in TYPO3 9.5

- Classes/ViewHelpers/TargetLinkViewHelper.php
Compare to #760, dokumented examples should also adopted
> [TASK] Adapt viewhelper example code

- Classes/Hooks/ItemsProcFunc.php
> [BUGFIX] Fix keys for $allLayouts to handle restrictions correctly

- Configuration/TCA/tx_news_domain_model_news.php
- Configuration/TCA/tx_news_domain_model_tag.php
I hope I did not forget anything. In simple tests, these changes seem to be sufficient.
Should close #799
> [FEATURE] Add possibility to translate tags

- Tests/Unit/Command/NewsImportCommandControllerTest.php
Obviously, no information needed.
> [TASK] Fix typo

- Classes/Domain/Model/News.php
> Check for existence of properties before formating

- Configuration/TCA/Overrides/tx_news_domain_model_news.php
> [TASK] Use '-' for slash-replacement in slug

- Configuration/TCA/Overrides/sys_category.php
- Configuration/TCA/Overrides/tx_news_domain_model_tag.php
> [TASK] Use '-' for '/'-replacement in slug

- Classes/ViewHelpers/Widget/Controller/PaginateController.php
> [FEATURE] Provide pagination information to TSFE register

- Classes/Domain/Service/NewsImportService.php
> FIX #870 Exception when importing tt_news with news_ttnewsimport

- Classes/Domain/Repository/AbstractDemandedRepository.php
When we worked with your extension we should been disable LanguageOverlayMode mode but it can't be possible without small modification in the code.
I modifed your code and it wil be cool if you apply this changes.
> Additional option to the generateQuery method

- Classes/Hooks/Backend/PageViewQueryHook.php
- ext_localconf.php
Hides inline tt_content elements in page view in typo3 9 only
> [BUGFIX] Fix #858 for typo3 v9 by adding PageLayoutView hook 

- Resources/Private/Partials/Category/Items.html
Add the attribute "data-namespace-typo3-fluid" to html viewhelper tag
> [BUGFIX] Add data-namespace-typo3-fluid

- Configuration/TCA/tx_news_domain_model_link.php
- Configuration/TCA/tx_news_domain_model_news.php
- Configuration/TCA/tx_news_domain_model_tag.php
> [TASK] Add renderType inputDateTime to datetime columns

- Resources/Private/Templates/Styles/Twb/Templates/ViewHelpers/Widget/Paginate/Index.html
> [BUGFIX] Add support for tag lists with pagination in twb template

- Documentation/AdministratorManual/BestPractice/Routing/Index.rst
* Before this change the pagination path to page 1 was not correct.
* See: Issu #895
> [DOC] Changes in routeEnhancer Documentation regarding pagination

- Configuration/TCA/tx_news_domain_model_news.php
Change TCA of l10n_parent column
from select to group type for performance reasons
> [TASK] Use group type for l10n_parent

- Documentation/AdministratorManual/BestPractice/Seo/Index.rst
Gets relevant as soon https://review.typo3.org/c/Packages/TYPO3.CMS/+/61568 is merged (or patch is applied)
> [TASK] add documentation how to define multiple sitemaps

- Classes/Utility/ClassCacheManager.php
> [BUGFIX] leave early when no proxy class is set

- Configuration/TCA/tx_news_domain_model_news.php
- ext_tables.sql
Changes news title from tinytext to varchar(255)
Resolves #1307
> change title from tintytext to varchar(255)

- Documentation/AdministratorManual/Configuration/TypoScript/Index.rst
> [DOCS] Add more TypoScript / Flexform default values

- Configuration/TCA/Overrides/tx_news_domain_model_news.php
- Documentation/AdministratorManual/BestPractice/Seo/Index.rst
- ext_tables.sql
Resolve https://github.com/georgringer/news/issues/1299
> [FEATURE] Add changefreq and priority for XML sitemap

- Documentation/AdministratorManual/BestPractice/ICalendar/Index.rst
config section is ignored otherwise.
> Add missing page key to config section

- Configuration/FlexForms/flexform_news.xml
> [TASK] Remove maxItems for selectedList

- Classes/Domain/Repository/CategoryRepository.php
> [BUGFIX] Fix entry level in category menu for TYPO3 10

- Classes/Domain/Model/Link.php
- Classes/Domain/Model/News.php
- Classes/Domain/Model/TtContent.php
fixes https://github.com/georgringer/news/issues/1376
> [TASK] Fix annotations

- Documentation/AdministratorManual/BestPractice/Seo/Index.rst
> [DOC] Index news records, don't index page itself (SEO)

- Classes/Domain/Service/AbstractImportService.php
- Classes/Domain/Service/CategoryImportService.php
- Classes/Domain/Service/NewsImportService.php
- Classes/Event/CategoryImportPostHydrateEvent.php
- Classes/Event/NewsImportPostHydrateEvent.php
- Classes/Event/NewsImportPreHydrateEvent.php
Usage of SignalSlot is also deprecated since TYPO3v10
> [TASK] Switch from SignalSlot to Event in Importer classes

- Documentation/AdministratorManual/BestPractice/AvailableContentElements/Index.rst
removeItems instead removeItem
> fixed little typo

- Classes/Domain/Model/News.php
- Classes/Hooks/BackendUtility.php
- Classes/Hooks/ItemsProcFunc.php
- Classes/Utility/ClassLoader.php
- Classes/Utility/TemplateLayout.php
- Classes/Utility/Url.php
- Classes/ViewHelpers/ImageSizeViewHelper.php
> [TASK] Replace deprecated string util methods

- Classes/Controller/CategoryController.php
Fixes issue that categories set by overwriteDemand get lost
> [BUGFIX] Respect categories from demand

- ext_tables.sql
> [BUGFIX] Fix SQL definition for related_link

- Documentation/DeveloperManual/ExtendNews/Demands/Index.rst
- Documentation/DeveloperManual/ExtendNews/Events/Index.rst
- Documentation/DeveloperManual/ExtendNews/ExtensionBasedOnNews/Index.rst
- Documentation/DeveloperManual/ExtendNews/Hooks/Index.rst
- Documentation/DeveloperManual/ExtendNews/Index.rst
- Documentation/Tutorials/Integration/Linkhandler/Index.rst
- Documentation/Tutorials/Templates/OverwriteDemandInFrontend/Index.rst
> [DOCS] Explain concept of "Demands"

- Documentation/AdministratorManual/Configuration/TsConfig/Index.rst
Fix double word.
Also, using terms like "easy" etc. to describe something is discouraged,
see Symfony docs styleguide.
---
Not part of commit message: Added some PR for things I noticed when reading. I can do more but did not want to create too many PR at once. I created small PR with usually one atomic change each so they can be easily reviewed and merged. If more is welcome, please let me know.
> [DOCS] Improve style

- Classes/Service/SlugService.php
> [BUGFIX] Take language id into account when generating a unique value in SlugService

- Documentation/Administration/Update/Index.rst
- Remove broken link
- Update information about versioning scheme to refer to semantic
versioning
Resolves: #1673
> [DOCS] Update information about versioning

- Documentation/Includes.rst.txt
- Documentation/Reference/TsConfig/Administration.rst
- Documentation/Reference/TsConfig/General.rst
- Documentation/Reference/TsConfig/Index.rst
- Documentation/Reference/TsConfig/Plugin.rst
refs https://github.com/georgringer/news/issues/1694
> [DOCS] Display TSconfig as confvals

- Classes/Utility/ClassCacheManager.php
[BUGFIX] Generated proxy class is broken
> FIXES #1584

- Resources/Private/Templates/Styles/Twb/Partials/List/Pagination.html
> [BUGFIX] Fix pagination style for Bootstrap 3

- Classes/Hooks/BackendUtility.php
Show/Hide a news-plugin in list-/page-module throws an Exception
```
PHP Warning: Trying to access array offset on value of type null in /var/www/html/public/typo3conf/ext/news/Classes/Hooks/BackendUtility.php line 138
```
> PHP Warning when show/hide news-plugin

- Classes/ViewHelpers/LinkViewHelper.php
> [BUGFIX] Fix "section" attribute in link tags

- Classes/ViewHelpers/LinkViewHelper.php
> [BUGFIX] Add "section" to link URL if uriOnly = 1

- Classes/ViewHelpers/Category/CountViewHelper.php
- Resources/Private/Templates/Category/List.html
> [FEATURE] Display number of news per category in Category Menu

- Classes/Seo/NewsXmlSitemapDataProvider.php
Make sure the generated XML-sitemap does not contain records from different workspaces.
Fixes georgringer/news#1721
> [BUGFIX] Add workspace-restriction to XML-sitemap

- Classes/ViewHelpers/RenderMediaViewHelper.php
with the 'fileIndex' argument, you can start with a different image
for example if your first image is a header image, you can start with the second one
> [FEATURE] Add 'fileIndex' argument

- Classes/TreeProvider/DatabaseTreeDataProvider.php
> [BUGFIX] Avoid warning undefined array key

- Classes/Domain/Model/News.php
Fixes deprecated usort return values from PHP 8.0 in News model
> [BUGFIX] #1777 usort return values in PHP 8.0

- Documentation/Reference/ViewHelpers/LinkViewHelper.rst
> closing tag on output preview was wrong

- Classes/Hooks/PageLayoutView.php
Whole params array should be sent to userfunction.
> [BUGFIX] extensionSummary Hook Call

- Classes/Hooks/Backend/RecordListQueryHook.php
Undefined array key "demand"
resolves #1830
> [BUGFIX] PHP8.1 warning in Administration module

- Classes/Seo/NewsAvailability.php
> additional check if the page arguments are set

- Classes/Seo/NewsXmlSitemapDataProvider.php
Undefined array key "useCategorySinglePid"
> [BUGFIX] PHP 8.1 warning in XML Sitemap DataProvider

- Classes/Backend/FormDataProvider/NewsRowInitializeNew.php
- Classes/Backend/RecordList/RecordListConstraint.php
- Classes/Domain/Repository/NewsRepository.php
- Classes/Utility/ConstraintHelper.php
- Tests/Functional/Repository/NewsRepositoryTest.php
> [BUGFIX] Use date aspect instead of $GLOBALS['SIM_EXEC_TIME']

- Classes/ViewHelpers/LinkViewHelper.php
> [BUGFIX] Proper check for news in workspace in LinkVh

- Documentation/Addons/NewsContentElements/Index.rst
Remove the empty citation on top created by incorrect indentation
> [Docs] Fix rendering error

- Classes/Domain/Service/NewsImportService.php
> [BUGFIX] fix type casting, these values are strings

- .gitattributes
Add .github directory and
.editorconfig to .gitattributes
> [TASK] Update .gitattributes

- Configuration/TCA/Overrides/z_misc_11_adoptions.php
- Configuration/TCA/tx_news_domain_model_news.php
> Loading Issue with large category tree

- Documentation/Tutorials/Templates/MultiCategorySelection/Index.rst
Changes Template to work with translated news and categories. georgringer/news#1991
> [DOC] Update Example Template Multi Category Selection

- Classes/ViewHelpers/MetaTagViewHelper.php
Additionally switch to the MetaTag API
> [FEATURE] Add attribute  to MetaTagVh

- Classes/Updates/PluginUpdater.php
> Fix Warning: Undefined array key "switchableControllerActions"

- Configuration/TypoScript/setup.typoscript
- Documentation/Tutorials/BestPractice/HideDetailPage/Index.rst
> [BUGFIX] Show news detail in insert record ce

- Configuration/TCA/Overrides/sys_category.php
Fixed TCA configs so its possible for images to add Alt Text and Link and Image overlay configuration options in the images.
Resolves: #2103
> [BUGFIX] sys_category -> images column TCA configs fixed

- Tests/Unit/Domain/Repository/NewsRepositoryTest.php
- Tests/Unit/ViewHelpers/LinkViewHelperTest.php
A new version of PHP-CS-Fixer has new things to fix.
> [CLEANUP] Fix code style issues

- Classes/Domain/Model/TtContent.php
Fix https://github.com/georgringer/news/issues/2131
> [BUGFIX] Properly handle ObjectStorage in tt_content domain model

- Configuration/TCA/tx_news_domain_model_news.php
> [Bugfix] Allow media files for news again

- Classes/Event/Listener/ModifyDatabaseQueryForRecordListingEventListener.php
- Configuration/Services.yaml
Use an event to hide the content elements linked in a news record in list view
Resolves: #2127
> [TASK] Hide again content elements in list module

- Configuration/TCA/Overrides/sys_template.php
- Configuration/TypoScript/SeoSitemap/constants.typoscript
- Configuration/TypoScript/SeoSitemap/setup.typoscript
- Configuration/TypoScript/Sitemap/setup.typoscript
resolves https://github.com/georgringer/news/issues/2117
> [FEATURE] Deprecate Legacy sitemap and provide new solution

- Classes/Seo/NewsXmlSitemapDataProvider.php
> [BUGFIX] Protect sitemap against missing category record

- .github/CONTRIBUTING.md
This PR fixes some outdated links and code examples in the contribution guide.
> [TASK] Fix links and code examples in contribution guidelines

- Classes/Domain/Repository/NewsRepository.php
> [BUGFIX] Fix undefined array key "single" in NewsRepository

- ext_tables.sql
> [TASK] Add index for parent relation in link table

- Tests/Functional/Fixtures/tags.csv
https://github.com/georgringer/news/issues/2214
> [Test] Remove duplicated entry in test data set

- Resources/Private/Language/locallang_be.xlf
> [TASK] Rename plugin names (and descriptions)

- Resources/Private/Language/locallang_db.xlf
> [TASK] Update locallang_db.xlf

- Classes/Command/ProxyClassRebuildCommand.php
> [BUGFIX] Ensure command compat with Symfony >= 7.x

- .github/workflows/core11.yml
- .github/workflows/core12.yml
> [BUGFIX] Use the PHP version from the CI matrix for the CGL checks

- Build/phpunit/FunctionalTests.xml
- Build/phpunit/UnitTests.xml
- align the XSD version with the loaded PHPUnit version
- drop template comments
> [TASK] Streamline the PHPUnit configuration files

- Documentation/Index.rst
This is a defined standard in the Documentations Team Recommendations
> [DOCS] Add start anchor to the index page

- Documentation/Index.rst
- Documentation/Reference/TsConfig/Index.rst
- Documentation/Reference/TypoScript/Index.rst
- Documentation/Tutorials/BestPractice/Index.rst
- Documentation/Tutorials/ExtendNews/Index.rst
- Documentation/Tutorials/Index.rst
- Documentation/Tutorials/Templates/Index.rst
- Documentation/UsersManual/Index.rst
- Documentation/UsersManual/Records/Index.rst
The rest is much easier to read and adjust this was, the output is also nicer
> [DOCS] Switch to using the new cards directive

- Resources/Private/Partials/Detail/Opengraph.html
> [BUGFIX] ogImage condition - don't render media of null

- Configuration/Sets/News/config.yaml
- Configuration/Sets/News/constants.typoscript
- Configuration/Sets/News/setup.typoscript
- Configuration/Sets/Sitemap/config.yaml
- Configuration/Sets/Sitemap/constants.typoscript
- Configuration/Sets/Sitemap/setup.typoscript
- Configuration/Sets/Twb4/config.yaml
- Configuration/Sets/Twb4/constants.typoscript
- Configuration/Sets/Twb4/setup.typoscript
- Configuration/Sets/Twb5/config.yaml
- Configuration/Sets/Twb5/constants.typoscript
- Configuration/Sets/Twb5/setup.typoscript
- Documentation/Administration/Configuration/Index.rst
No further changes made, should be unbreaking.
Resolves: https://github.com/georgringer/news/issues/2475
> [FEATURE] Add site sets as drop in replacements for TypoScript includes

- .github/workflows/core12.yml
- .github/workflows/core13.yml
- Classes/Domain/Repository/NewsRepository.php
Fix the datemenu query for sqlite 
Resolves: #2208
> [TASK] Fix query for sqlite

- Documentation/Tutorials/ExtendNews/ProxyClassGenerator/Index.rst
> [DOC] ProxyClassGenerator - exclude class from dependency injection

- Classes/Domain/Repository/NewsRepository.php
- composer.json
…etLanguageOverlayMode()
Resolves: https://github.com/georgringer/news/issues/2558
> [BUGFIX] Use language aspect in NewsRepository

- Documentation/Tutorials/BestPractice/Routing/Index.rst
> [DOCS] Use page argument in routePath

- Configuration/FlexForms/flexform_category_list.xml
- Configuration/FlexForms/flexform_news.xml
- Configuration/FlexForms/flexform_news_date_menu.xml
- Configuration/FlexForms/flexform_news_detail.xml
- Configuration/FlexForms/flexform_news_list.xml
- Configuration/FlexForms/flexform_news_search_form.xml
- Configuration/FlexForms/flexform_news_selected_list.xml
- Configuration/FlexForms/flexform_tag_list.xml
> [BUGFIX] Replace indexed array keys for items by label and value tags

- composer.json
The following tool has been used to order all sections in the composer.json file:
https://github.com/ergebnis/composer-normalize
> [TASK] Normalize composer.json

- Configuration/FlexForms/flexform_news_detail.xml
> Add listPid to FlexForm of detail plugin

- composer.json
> [TASK] Set typo3/cms-install as hard dependency (#2624)

- Tests/Functional/ViewHelpers/ExtensionLoadedViewHelperTest.php
> [TASK] Adopt test after fluid changes

- Resources/Private/Partials/List/Item.html
- Resources/Private/Templates/News/Detail.html
- Resources/Private/Templates/Styles/Twb/Partials/General/AdditionalInformation.html
- Resources/Private/Templates/Styles/Twb5/Partials/General/AdditionalInformation.html
This fixes https://github.com/georgringer/news/issues/2666
> [BUGFIX] Output timestamp including timezone for datePublished meta data

- Classes/Event/Listener/ModifyFileReferenceControlsEventListener.php
Resolve https://github.com/georgringer/news/issues/2676
> [BUGFIX] Fix #2676 - Avoid fatal error by assigning images in backend

- Documentation/Reference/TsConfig/Index.rst
- Documentation/Reference/TsConfig/NewContentElementWizard.rst
> [docs] Add example for setting default values in New content element wizard
