georgringer/news

Resources/Private/Templates/Styles/Twb/Templates/News/List.html

One row is nested in another row so the negative margin is doubled and so the list does not correctly align with other content on the page.
The outer row is removed since it's not necessary here.
Resolves #120

[BUGFIX] remove one row class from list container

---

Classes/Domain/Repository/AbstractDemandedRepository.php

this is a followup to this patch:
https://github.com/georgringer/news/pull/139
i found this bug by trying to use the dateMenuAction to render a datemenu in frontend.
the countByDate() function in NewsRepository is using the raw sql which comes from findDemandedRaw().
non-numeric values need to be quoted in the raw sql string, to avoid a sql-error in countByDate() function.

[BUGFIX] quote non-numeric values in raw sql

---

Classes/Backend/FormDataProvider/NewsFlexFormManipulation.php
ext_localconf.php

Flex form manipulation via hook getFlexFormDSClass in method
getFlexFormDS() will no longer work with core version >= 8.5
since the method is not called anymore within core.
The current usage of the hook basically hides fields flex form
fields in FormEngine and adds a foreign_table_where in another
field.
This does not affect the data handler, so this hook can be
transferred to a FormEngine data provider that is placed
between TcaFlexPrepare and TcaFlexProcess, not using the
additionally available hooks of the new core data structure
handling.
Related: #78581

[TASK] Adapt to breaking core hook getFlexFormDSClass

---

Documentation/AdministratorManual/Configuration/TypoScript/Index.rst

Config must be a string (active/archived), nor an integer.
I update the properties table and the example.

Update configuration of archiveRestriction

---

Classes/Domain/Repository/AbstractDemandedRepository.php

reorder the if-statements to check which typo3 version is used.

[BUGFIX] make datemenu work again on 7.6

---

Classes/ViewHelpers/RemoveMediaTagsViewHelper.php
Classes/ViewHelpers/RenderMediaViewHelper.php
Resources/Private/Partials/List/Item.html
Resources/Private/Templates/News/Detail.html

Allows to display media bodytext/teaser without the usage of RTE images.
The ViewHelper replaces [media] tags in teaser/bodytext with the attached media files.

[FEATURE] add ViewHelper to display media files inline

---

Classes/Controller/NewsController.php
Classes/Domain/Repository/CategoryRepository.php
Classes/Domain/Repository/TagRepository.php

Do not create query parts, if the list of categories or tags
is empty. This will cause invalid SQL queries to be cached by
extbase query cache and will cause either wrong output or even
SQL errors, depending on the query getting cached.

[BUGFIX] Check for non-empty tag or category lists

---

Classes/Hooks/BackendUtility.php

The tag list and search form flexform definitions do not use the categories field.
When the foreign_table_where setting is added there is no renderType set for 'settings.categories'. This results in an exception when the plugin is edited.

[BUGFIX] add check before category restriction is added to flexforms

---

Configuration/TCA/tx_news_domain_model_link.php
Configuration/TCA/tx_news_domain_model_news.php

MySQL strict mode complains about missing l10n_parent field values
if being used in strict mode. The solution is to defined the missing
default values for the affected field names.

[BUGFIX] Copying news with MySQL strict mode fails

---

Classes/Hooks/DataHandler.php

... using a non-admin BE user
This fixes a bug that can be reproduced the following way : 
1. Log in as a non-admin TYPO3 user in BE
2. Create a news, assign a sys_category to it
3. From the List module, click the "Enable/disable" button on this news
4. The categories are not associated with the news anymore

[BUGFIX] Fixed lost categories relations when enabling/disabling a news from list module

---

Classes/ViewHelpers/LinkViewHelper.php

The VH does not work with CompilableInterface and without renderStatic method.
The best solution for now is to remove the CompilableInterface, because the
render method contains a lot of $this references.

[BUGFIX] Remove CompilableInterface

---

Documentation/AdministratorManual/BestPractice/Rss/Index.rst

According to the RSS 2.0 specification [1], the channel language
attribute contains "-" as separator between primary-code and sub-code.
[1] http://www.rssboard.org/rss-specification#optionalChannelElements

[DOC] Fix example for rss.channel.language

---

ext_tables.sql

Use int instead of text to decrease reserved memory for field content_element

[TASK] adapt db field type for inline relation

---

Documentation/AdministratorManual/BestPractice/Rss/Index.rst

according to my tests, constant settings are in plugin.tx_news, not in plugin.tx_news.settings.list

constant settings are in plugin.tx_news

---

Classes/Utility/Page.php

Using preview of single news item from workspaces might require to add '-1' to 'plugin.tx_news.settings.startingpoint'.
This fix ensures that no wrong child uids are fetched for 'pid = -1'.
Resolves: #271

[BUGFIX] Don't extend pid list for startingpoint=-1

---

Documentation/DeveloperManual/ExtendNews/ExtendFlexforms/Index.rst

The hook was renamed in Version 3.2.0: https://docs.typo3.org/typo3cms/extensions/news/Misc/Changelog/3-2-0.html#rename-some-hooks

Fix documentation about updateFlexforms hook

---

Classes/Controller/NewsController.php

By adding category and tags always to the assigned values for 
the list signal, we ensure that attached signals can use a reliable set
of params that they also need to return.

[BUGFIX] Always provide category and tag values for list signal

---

Resources/Private/Templates/News/List.xml

This wrong syntax caused exceptions in ImageService, because of passed strings, instead of expected objects.

[BUGFIX] Fix wrong fluid inline syntax in List.xml

---

Classes/Controller/AdministrationController.php
Configuration/TSconfig/Administration.txt
Documentation/AdministratorManual/Configuration/TsConfig/Index.rst
Resources/Private/Templates/Administration/Index.html
ext_localconf.php

Define whether filters should be available in backend module or not. By default, all the filters are enabled. The available filters are:
- searchWord
- timeRestriction
- topNewsRestriction
- hidden
- archived
- sortingField
- number
- categories
- categoryConjunction
- includeSubCategories
Note: The filters `categoryConjunction` and `includeSubCategories` can only be enabled when the filter `categories` is enabled.
Resolves #229

[FEATURE] Make it possible to hide filters in backend module

---

Classes/Controller/NewsController.php
Configuration/TypoScript/setup.txt

Thix Bugfix fixes the problem, when you want to insert a shortcut (insert record) of a news record on a page, where also the detail view is displayed. The action should use the setting 'singleNews' if the view is called via shortcut whether there is already a news record on the page or not.

[BUGFIX] Wrong news record in shortcut content element if on detail page

---

Classes/Hooks/ItemsProcFunc.php

The else branch is superfluous, thus removed.

[TASK] Remove unnecessary else branch

---

Classes/Xclass/InlineRecordContainerForNews.php

Now you won't get the "Invalid Value"-Message on tt_content preview.

[BUGFIX] #357 Add tt_content ctype labels to pagelayoutview 

---

ext_localconf.php

Core: Error handler (BE): PHP Notice: Undefined index: cache_news_category in typo3conf/ext/news/ext_localconf.php line 74

Fix PHP Notice in ext_localconf.php

---

Resources/Private/Templates/ViewHelpers/Widget/Paginate/Index.html

This is quite a no-brainer. The condition that checks whether to generate the `<link rel="prev/next">` tags should not use `settings.list.paginate` but `settings.list.paginate.prevNextHeaderTags`.

[BUGFIX] Make option list.paginate.prevNextHeaderTags work

---

ext_tables.php

Fix a small typo.
I found this change while searching for a similar solution in a different extension.
However, I've been wondering why the fix is applied to versions 9+ only? IMO it is also needed for every version 8.x.

[BUGFIX] Fix spelling

---

Resources/Private/Templates/Styles/Twb/Layouts/Detail.html
Resources/Private/Templates/Styles/Twb/Layouts/General.html
Resources/Private/Templates/Styles/Twb/Partials/Category/Items.html
Resources/Private/Templates/Styles/Twb/Partials/General/AdditionalInformation.html

This will remove the < html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers" > in the rendered code of the website.

[BUGFIX] Prevent output of ViewHelper xmlns-attributes

---

Classes/Controller/NewsController.php

Using stdWrap on TS settings now passes the correct content value
to the stdWrap function.

[BUGFIX] Pass correct content to stdWrap function

---

Classes/ViewHelpers/MetaTagViewHelper.php

The current implementation of the `MetaTagViewHelper` also prepends `TYPO3_SITE_URL` to external urls if `forceAbsoluteUrl=1` is set. That is a problem when you have already fully qualified external image urls e.g. because the images are stored in an S3 Bucket.
The more it would also prepend `TYPO3_SITE_URL` to non urls if `forceAbsoluteUrl=1` is set.
My proposed fix for this is inspired by how TYPO3 Core addresses that issue:
https://github.com/TYPO3-CMS/extbase/blob/96fffc2b245dc29a78bcb06a64cdb9d138f169c9/Classes/Service/ImageService.php#L85-L87

Fixes already fully qualified urls being prefixed for Open Graph Protocol tag

---

Classes/Hooks/Backend/RecordListQueryHook.php
Classes/Service/CategoryService.php

As this is a minor correction, I don't know if it needs an specific issue, so feel free to reject/ask if issue needs to be open.
With these corrections, plugin will work in postgres installations (without it Typo3 raises exceptions and some user pages become impossible to be edited in Pages module and News administration module won't work).

Improved compatibility for postgres installations

---

Documentation/AdministratorManual/BestPractice/Realurl/Index.rst

- Add `:linenos:` for for line numbering code block realurl "Advanced example"
- Fix line number in explanation
Note: As this is a trivial change, I did not create an issue. This is my first PR for "news". I read the contribution guidelines and hopefully followed everything correctly. If you want anything changed in this PR, just let me know.

Documentation change: fix line numbers in realurl example

---

Classes/Utility/Cache.php

I noticed that editing the translation of a news record in typo3 8.7.15 does not clear the cache of that translated page.
The reason is: extbase always exposes the original uid, not the translated one.
I solved that here by using the sort-of™ private method `_getProperty` to access the real uid. That will tag the page with the original uid and the translated uid. That covers translated news nicely without clearing too much.

also add the localized uid as cache tag

---

Classes/Service/CategoryService.php

The use of $GLOBALS['TT']->setTSlogMessage() is not supported anymore and leads to error messages in log files when using Typo3 >= 8.7 when saving news entries.
See https://docs.typo3.org/typo3cms/extensions/core/8.7/singlehtml/Index.html#breaking-73504-make-timetracker-a-singleton for details

[BUGFIX] Use instance of TimeTracker instead of $GLOBAL['TT']

---

Documentation/Misc/Changelog/7-0-0.rst

- The section "Allow more options for file preview" refers to 
the option records.advancedMediaPreview. Writing this
explicitly may make it a little easier to find.

[DOC] Add clarification to Changelog for 7.0.0

---

Classes/Utility/Cache.php

In that case we can simply use the news table name as a cache tag.
That cache tag is automatically flushed by the TYPO3 DataHandler when
a record is updated in the backend.

[BUGFIX] Add a cache tag for listings without a configured startingpoint

---

Resources/Private/Templates/News/Detail.html

#760 fix for default detail view

 Render related links as link in TYPO3 9.5

---

Documentation/Settings.cfg

- Remove commented out examples, because the links no longer exist
- Add link for issues and repo because that will then show up as
"Related links" on docs.typo3.org
- Move sections to comply to generally used order

[DOC] Add links to Settings.cfg

---

ext_conf_template.txt

If `advancedMediaPreview = true`:
---
If `advancedMediaPreview = 1`:

Set advancedMediaPreview to 1 instead of true

---

Configuration/TypoScript/setup.txt

There are no difference between css_styled_content and fluid_styled_content
styles.content.textmedia.* constants in actual supported TYPO3 versions.
For this reason, the condition is removed and the lightbox settings are retrieved
from styles.content.textmedia.linkWrap.*
The comment was simplified to fluid_styled_content, because of the fact that
css_styled_content is deprecated in the supported TYPO3 versions.
Likewise, deprecations in TYPO3 9.5 LTS (TypoScript.strictSyntax feature toogle)
are no longer thrown by removing the old
Fixes: #826

[TASK] Remove superfluous TypoScript condition

---

Classes/Service/SlugService.php
Classes/Updates/NewsSlugUpdater.php
Classes/Updates/RealurlAliasNewsSlugUpdater.php
Documentation/AdministratorManual/Migration/Index.rst
Documentation/AdministratorManual/Migration/MigrationFromRealurl/Index.rst
ext_localconf.php

Introduces a new installtool upgrade wizard, which appears,
if DB:table tx_realurl_uniqalias exists with
valid realurl aliases for empty news slugs.
This offers possibility for news with similar titles
have same url like in realurl.
EXT:news v7.x, TYPO3 v8.7 and v9.5

[FEATURE] Add realurl alias migration for news slugs

---

Classes/Domain/Repository/NewsRepository.php

The `NewsRepository` did not respect the `setSplitSubjectWords` setting

[BUGFIX] Allow setSplitSubjectWords to be false

---

Classes/Utility/Page.php

As defined in PHP doc description for Page::setRegisterProperties()
expected object of mixed type (object or array) will be handled correct.
refs #880

[BUGFIX] Handle array's within method Page::setRegisterProperties

---

Classes/Domain/Repository/NewsRepository.php

The `ORDER BY` part has to be removed before any other constraints are added to the query.
The actual implementation cannot remove the `ORDER BY` and therefore an exception is thrown. The exception message says that the query syntax is invalid.
**NewsRepository.php**
```php
/**
* The repository for News.
*/
class NewsRepository extends \GeorgRinger\News\Domain\Repository\NewsRepository
{
/**
* @var array
*/
protected $defaultOrderings = [
'sorting' => \TYPO3\CMS\Extbase\Persistence\QueryInterface::ORDER_ASCENDING,
];
}
```
**NewsControllerSlot.php**
```php
<?php
namespace XXX\XXXNews\Slots;
use GeorgRinger\News\Domain\Model\Dto\NewsDemand;
use XXX\XXXNews\Domain\Repository\NewsRepository;
class NewsControllerSlot
{
/**
* @var NewsRepository
*/
private $newsRepository;
public function …
```

Fix strip of "ORDER BY" in statistics query

---

Configuration/TCA/tx_news_domain_model_link.php
Configuration/TCA/tx_news_domain_model_news.php
Configuration/TCA/tx_news_domain_model_tag.php

In order to have localization handling with both l10n_parent and
l10n_source in place, l10n_source needs to be defined as column
in $GLOBALS['TCA'] as well.
Basically DataHandler::fillInFieldArray() is checking for those
values and does not distinguish correctly between system internal
and entity specific properties (always has been like that in TYPO3):
https://github.com/TYPO3/TYPO3.CMS/blob/5133578a4e534873cf3777cc9c6c579076a45250/typo3/sysext/core/Classes/DataHandling/DataHandler.php#L1546
Resolves: #885

[BUGFIX] Add missing l10n_source columns

---

ext_tables.sql

To be able to handle dates before 1901, the datetime and archive fields are changed to big int. (example imports of old articles)

[TASK] Change datetime and archive fields to bigint

---

Classes/Controller/NewsController.php

By hardcoding these values before, it was not possible to overwrite TypoScript
settings in foreign namespaces. This shouldn't be an issue for typical use
cases. In case you register further plugins on your own, e.g. "news_recent",
this will not be able to be processed as expected.
Resolves: #907

BUGFIX: Allow to overwrite TypoScript settings

---

Classes/Xclass/InlineRecordContainerForNews.php

`$recordTitle` wasn't defined anywhere. 
`$label = $data['recordTitle'];` implifies, that this was the old variable name.

[BUGFIX] Replace undefined var $recordTitle

---

Classes/Utility/ClassCacheManager.php

The constructorLines property is never unsetted in ClassCacheManager.
This results in added constructors for subsequent classes if this
property is set.
Resetting this property to an empty array fixes this issue.

[Bugfix] Constructor in subsequent proxyclasses

---

Classes/Backend/FormDataProvider/NewsFlexFormManipulation.php

The check is already present in the backend hook but not in the
form data provider.
Resolves: #854

[BUGFIX] Check for the category setting to exist when adding constraints

---

Classes/Hooks/ItemsProcFunc.php

If don't set the feature "allowedColPos" and you have defined more then one optiongroups, after the execution you get only the last defined optiongroup. I think, it's better to use $key as identifier instead of $layout[1].

Get only last defined optiongroup

---

Classes/Updates/RealurlAliasNewsSlugUpdater.php

This fixes a failing result message for tx_realurl_uniqalias update wizard, when executed,
but no changes was written into news table.
This can be in case of:
* no news entries matching any found tx_realurl_uniqalias entry
* update wizard was executed before, and opened for re-run
* path segment for matching news entries already are set
refs #949

[BUGFIX] Return true for executed wizard, also if no update queries necessary

---

Classes/DataProcessing/AddNewsToMenuProcessor.php

To make sure that even an empty result of the database query will not throw an exception, there must be an additional check.

Return must be an array

---

Classes/Hooks/DataHandler.php

Currently in TYPO3 8.x versions news will try to sanitize the title even if the title is not set in the case of switching the news type to internal/external link.
So we prevent the title to be sanitized if not even set in the fieldArray.
Would be related to issue #1054

[BUGFIX] prevent sanitizing title if title is not set in fieldArray

---

Documentation/DeveloperManual/ExtendNews/ExtendFlexforms/Index.rst

Removed FlexFormHook examples for non supported versions; Replaced `PATH_site` with `Environment::class`; Imported classes;

Updated "extend flexforms" documentation

---

Classes/Service/SlugService.php

When a news title contains a slash the slug update wizard will not
remove those. This will cause broken routing. With this change the TCA
configuration is taken into consideration which results in removal of
slashes.
Fixes #1088

[BUGFIX] Use SlugHelper::generate in order to considerate slug field TCA configuration

---

Configuration/TCA/Overrides/sys_category.php
Configuration/TCA/tx_news_domain_model_news.php
Configuration/TCA/tx_news_domain_model_tag.php

Reasons:
1. typo3/sysext/core/Classes/Configuration/Richtext.php, public function getConfiguration uses "default" anyway at the very last point of the fallback-chain if no richtextConfiguration was explicit set via e.g. PageTS or TCA
2. function getConfiguration was broken till now and did not take in account the settings defined via TCA
3. this patch: https://review.typo3.org/c/Packages/TYPO3.CMS/+/61193/3 (under review) will fix the issue of ignoring TCA settings; but the value of RTE.default.preset, set within custom extension via PageTS, would be ignored, since "default" is set in the TCA of the news-extension. 
Get more details at the commit message within provided link & feel free to ask

[BUGFIX] Remove "default" richtextConfiguration from TCA

---

Classes/Service/AccessControlService.php

If adding an additional field for category relations to the news element it is necessary to take the **fieldname** of the default category implementation into account. The class _AccessControlService_ is used in _DataHandler::processDatamap_preProcessFieldArray()_ to apply/keep categories the user has no access to. If not using the **fieldname** the custom category field has an impact to the **categories** field, values of the custom field were transferred to the default one.

[BUGFIX] Take account of the fieldname for category relations in AccessControlService

---

Resources/Private/Partials/Detail/MediaVideo.html

If you choose a youtube video element within a news item the fluid html namespace tag is rendered because the data attribute is missing here.

[BUGFIX] Prevent rendering of html tag if video is rendered

---

Configuration/TCA/tx_news_domain_model_news.php

The path_segment field will be visible in a non-live workspace
when a news record is created. Thus it can be filled initially
but not changed afterwards in non-live workspaces which is the
only possible behaviour for unique fields.
fixes #1119

[BUGFIX] don't show path_segment when in non live workspace

---

Documentation/AdministratorManual/Configuration/TypoScript/Index.rst

* The previous version was misleading

[DOC] Better description for "archiveRestriction = active"

---

Classes/Domain/Service/NewsImportService.php

The `path_segment` is currently not set when using the `NewsImportService`. I also thought about adding the path segment using  the `NewsSlugHelper` if `$importItem['path_segment']` is not set. But then again it is easy enough to generate the path segment outside the `NewsImportService` and maybe not everybody wants it to be set.
What do you think? Do we need a `!empty($importItem['path_segment'])` check because the path segment was not used until now?

[BUGFIX] Fix path_segment not set in NewsImportService

---

Classes/Controller/AdministrationController.php

The wrong return URL when creating a new record
caused to show the BE inside the module's frame again.

[BUGFIX] Create valid returnUrls in BE module

---

Classes/Controller/NewsController.php

This commit fixes a typo in a setting name, NewsController now checks for `settings.detail.pageTitle` properly.

[BUGFIX] Check for correct pageTitle setting

---

Classes/Domain/Repository/NewsRepository.php

When excludeAlreadyDisplayedNews was used in combination with
hideIdInList, the latter condition replaced the first, because
the same array key was used.

[BUGFIX] Fix excludeAlreadyDisplayedNews condition

---

Classes/Backend/RecordList/RecordListConstraint.php
Classes/Controller/AdministrationController.php
Resources/Private/Templates/Administration/Index.html
ext_tables.php

Hi there,
this fixes #1271
Some hard coded backend module routes had the /module prefix which does not work in TYPO3 9.5.16 and presumably any version of 9.5. At least I could not find any changes related to backend module routing.
This fixes our TYPO3 9.5.16 instance where the previous routes resulted in an exception being thrown. See #1271 for details.
I'm curious where the /modules comes from or where it would be needed. Maybe I'm just missing something obvious.
Kind regards
Jona

[BUGFIX] Use correct module routes

---

Classes/Controller/ImportController.php

News Import module fails to load in TYPO3 10 as the function `BackendUtility::getModuleUrl()` no longer exists (Deprecation #85113). This is a small patch to use `$uriBuilder->buildUriFromRoute()` instead

[BUGFIX] Update deprecated function call in News Import module

---

Configuration/Extbase/Persistence/Classes.php

Apply breaking change #87623 from TYPO3 CMS Core ChangeLog
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html
TypoScript Configuration in setup.txt is left untouched for backward compatibility.

Add Extbase persistence configuration to PHP

---

Classes/Backend/RecordList/RecordListConstraint.php

Use correct param order for strpos() call. This makes
the BE search form working again in Core v9.
Fixes: #1311

[BUGFIX] Determine current route correctly

---

Classes/Controller/NewsController.php
Classes/Domain/Repository/CategoryRepository.php
Configuration/TypoScript/setup.txt

Translation of category titles is now handled correctly regarding current sys_language by default, removes a deprecated property
resolves: #1185
closes: #1059

[BUGFIX] respect sys_language in FindInList by default

---

Classes/Backend/RecordList/RecordListConstraint.php
Classes/Hooks/Backend/RecordListQueryHook.php

Remove a lot of outdated code, which stems
from Core v8 times.
This removes a call to andWhere('') which now
causes an exception in DBAL.

[BUGFIX] BE module category search

---

Configuration/TCA/tx_news_domain_model_news.php

Video and Audio filetypes were using the incorrect palettes. Checked the core palette use and these match the filetypes for v9 and v10.
Incorrect palette:
P.S. would be nice if this PR could count for hacktoberfest :D
https://hacktoberfest.digitalocean.com/hacktoberfest-update

[BUGFIX] show correct overlay palette for video and audio filetypes

---

Classes/Service/SlugService.php

tx_realurl_uniqalias.value_id of translated news is set to the uid of the default news entry combined with the sys_language_uid.
Therefore translated news were not mapped, due to uid mismatch.
This extends the corresponding query to check on tx_news_domain_model.news.l10n_parent in tx_realurl_uniqalias.value_id for the specific sys_language_uid.

[BUGFIX] Map translated news aliases

---

Classes/Seo/NewsXmlSitemapDataProvider.php

The timezone correction when generating the sitemap did not cope with DST correctly. Now the offset is calculated at the datetime of the news itself.

[BUGFIX] Correctly adjust timezone in sitemap

---

Resources/Private/Templates/News/List.ical

DTSTAMP must be in UTC.
DTSTART/END should have TZ offset included.
ical files must use CRLF.

[BUGFIX] Use correct time in ical

---

Documentation/AdministratorManual/BestPractice/Routing/Index.rst

Just a small fix to make the `LocaleModifier` work in the shown example

[DOC] Fixed locale for LocaleModifier example

---

Classes/ViewHelpers/RenderMediaViewHelper.php

The usage of the cropping information was very outdated
and the new version is needed for TYPO3 10.4.11+

[BUGFIX] Fix invalid crop usage in RenderMediaViewHelper

---

Documentation/AdministratorManual/BestPractice/AvailableContentElements/Index.rst
Documentation/AdministratorManual/BestPractice/Index.rst

Based on my [question](https://stackoverflow.com/questions/65477411/typo3-configure-available-types-for-tx-news-content-element-relation/) on StackOverflow I'd like to add my findings to the documentation.

[DOCS] Add documentation to limit available content element CTypes

---

Classes/Xclass/InlineRecordContainerForNews.php
composer.json

The Core changed the markup for header fields inside IRRE, so this is adjusted as well.

[BUGFIX] Adjust the IRRE xclass to match v10.4.12

---

Configuration/TCA/tx_news_domain_model_news.php

This pull request simply hide the field `editlock` for a non admins user.

[BUGFIX] Hide editlock for non admins

---

Classes/ViewHelpers/HeaderDataViewHelper.php
Configuration/TypoScript/constants.txt
Configuration/TypoScript/setup.txt
Documentation/AdministratorManual/BestPractice/Routing/Index.rst
Documentation/AdministratorManual/BestPractice/Rss/Index.rst
Documentation/AdministratorManual/Templates/ViewHelpers/HeaderDataViewHelper.rst
Resources/Private/Templates/News/List.atom
Resources/Private/Templates/News/List.xml

To be able to have multiple RSS feeds without adapting the templates,
the page type number is now in a constant and a setting.
Additionally some changes where made in the feed templates:
*  As the output of the uri.page view helper gets escaped by default, the chaining to the format.htmlentities view helper was removed
See absense of $escapeChildren and $escapeOutput in https://github.com/TYPO3/TYPO3.CMS/blob/9.5/typo3/sysext/fluid/Classes/ViewHelpers/Uri/PageViewHelper.php
*  The Atom feed id must be an absolute URI
See: https://validator.w3.org/feed/docs/warning/RelativeSelf.html
*  View helpers in attributes are migrated to inline notation for better validation in IDEs

[TASK] Define a setting for the typeNum of the rss feed

---

Classes/Backend/FormDataProvider/NewsFlexFormManipulation.php
Classes/Controller/AdministrationController.php
Classes/Controller/CategoryController.php
Classes/Controller/NewsController.php
Classes/Domain/Model/Category.php
Classes/Domain/Model/Link.php
Classes/Domain/Model/News.php
Classes/Domain/Model/Tag.php
Classes/Domain/Model/TtContent.php
Classes/Domain/Service/AbstractImportService.php
Classes/Domain/Service/CategoryImportService.php
Classes/Domain/Service/NewsImportService.php
Classes/Hooks/Backend/RecordListQueryHook.php
Classes/Hooks/BackendUtility.php
Classes/Hooks/ItemsProcFunc.php
Classes/Hooks/PageLayoutView.php
Classes/Updates/NewsSlugUpdater.php
Classes/Updates/RealurlAliasNewsSlugUpdater.php
Configuration/Services.php
Tests/Unit/Controller/NewsControllerTest.php
Tests/Unit/Controller/TagControllerTest.php
composer.json

Classes
Most classes that called other classes either with objectManager or GeneralUtility have been migrated to DI and can be found on the __construct() function.
Services.php
In order for the DI to work the calsses have to be set to public. This can be achieved by adding the public attribute in the Services.yaml but it costs time since everytime the extension is called, these classes will be validated. Instead in the Services.php the classes will only be validated if they are called therefore saves time.
Domain Models
I needed to test the imports and Georg pointed me to another extension which i used. The import was successfull but the results brought some problems. The import, imports only the delivered values, so if there is no teaser, then the entry in the Database is set to null. …

Symfony Dependency Injection (DI)

---

Classes/Domain/Repository/NewsRepository.php

With this the preview of hidden translated news in strict language mode
(Fallback Type = strict) works.
Related: #1483

[BUGFIX] Preview of translations in strict language mode

---

Configuration/Services.yaml

Domain models should not be scanned during DI Container building, since
entities are not meant to be services. The actual bug that results of
this missing configuration line is an exception which ocurrs when
the extbase ClassSchema is built in the same request as the DI Container
scanned all classes.
The issue this PR targets is https://github.com/georgringer/eventnews/issues/102

[BUGFIX] Exclude domain models from DI container scanning

---

Classes/Controller/AdministrationController.php

Default still is to show the localization view, but setting module.localizationView = 0 is now adhered.

[BUGFIX] module.localizationView can be disabled

---

Classes/Domain/Model/Dto/NewsDemand.php

Year, month and day are used for mktime() calls mainly,
which expects those values to be integers, otherwise a
PHP warning is triggered.

[BUGFIX] Ensure Demand properties have correct data type

---

Documentation/AdministratorManual/BestPractice/IntegrationWithTypoScript/Index.rst

The Option was used in MS Internet Explorer for creating dashed lines around already clicked links but has been removed.

Remove noBlur = 1

---

Resources/Private/Templates/News/List.ical

One can't subtract a number from an object.
So make sure we use actual timestamps to do calculations.

[BUGFIX] Create valid DTSTAMP in List.ical

---

Resources/Private/.htaccess

Add if statement to check Apache version and use outdated
access control directives only if older Apache version.
Resolves: #1543

[TASK] Handle access control for newer Apache versions

---

Documentation/DeveloperManual/ExtendNews/AddCustomType/Index.rst

Without the array key, the configuration for news type 0 would be overwritten. News with type 0 are not displayed anymore.

Fix subclass registration

---

Configuration/TCA/tx_news_domain_model_news.php

With rtehtmlarea_images set, the reference index update throws exception

[BUGFIX] Remove not available softref from tca

---

Configuration/Extbase/Persistence/Classes.php

To avoid confusion, it is better to set explicit keys when register subclasses.

[TASK] Add explicit keys on subclasses registration

---

Classes/Domain/Model/News.php
Resources/Private/Templates/News/Detail.html

In the "Detail" view there is currently no possibility to view the "related news" sorted with the manual method.
I implemented it with a new methods in News Domain Model "getRelatedFromSortedByForeign" which consequently allow to use the relatedFromSortedByForeign array in the Fluid Template "Detail.html"
Relate to issue #1545 "In Detail View is not possible to show related news sorted manually "

[ FEATURE ] In Detail view showing related news sorted by sorting foreign #1563

---

Resources/Private/Language/locallang.xlf

The overview is neither a sentence nor is the total count of pages an ordinal number.
This has been marked as incorrect in accessibility reviews.

[TASK] Remove trailing dot from pagination overview

---

Configuration/TCA/Overrides/pages.php

The file news_only was renamed to `news_only.tsconfig`. Therefore, the path in `registerPageTSConfigFile` should also be changed.

Fix path to news_only.tsconfig

---

Documentation/AdministratorManual/Configuration/TsConfig/Index.rst

The textrole tsconfig does not exist. Since it is TypoScript
syntax, the role typoscript can be used, as in:
:typoscript:`something`.
See Includes.rst.txt

[DOCS] Fix formatting for typoscript

---

Documentation/AdministratorManual/Configuration/ExtensionConfiguration/Index.rst
Documentation/AdministratorManual/Configuration/Index.rst
Documentation/AdministratorManual/Configuration/TsConfig/Index.rst
Documentation/AdministratorManual/Installation/Index.rst
Documentation/UsersManual/Records/News/Index.rst

The extension is no longer configured in the Extension Manager,
but configured in the Extension Configuration. Some files, labels
and decriptions are changed to reflect that.
Also in some internal references (:ref:) the anchor text was removed.
This way the header of the linked to section will automatically be
used as anchor text in the link.

[DOCS] Changes related to Extension Configuration

---

Documentation/Administration/Installation/Index.rst

- Fix error in formatting: A newline must exist between different
levels of bullet lists or numbered lists
- The order "go to Extension Manager" and then install via Composer
was confusing. This was changed.
- The labels in the Extension Manager have changed. This is now
fixed
- The extension is no longer configured in the extension manager,
change the phrase to reflect that.
- Fix indenting to avoid formatting problems in "Important"
admoninition

[DOCS] Fix installation page

---

Classes/Controller/NewsController.php

This fixes
PHP Warning
Core: Error handler (BE): PHP Warning: Undefined array key "settings" in /var/www/public/typo3conf/ext/news/Classes/Controller/NewsController.php line 654
in the News Administration.
Setup:
Typo3 11.5.5 in debug mode
php 8.0

[BUGFIX] Fix notices in backend

---

Documentation/Tutorials/Templates/Snippets/Index.rst

There is no need to change the text of the back link via JavaScript. Translation should still be done via the TranslateViewHelper.

Remove unnecessary part .text('Back') in JavaScript Snippet

---

Classes/Service/CategoryService.php

Add fallback if $title is empty and $default argument is NULL. Return an empty string instead of NULL.

[BUGFIX] Return empty instead NULL (#1740)

---

Documentation/Reference/TypoScript/GeneralSettings.rst

This would solve #1778.
It adds a hint to the TypoScript Setting.

[DOC] #1778 Add hint for EXT:numbered_pagination in list.paginate settings

---

Documentation/Tutorials/ExtendNews/Events/Index.rst

To avoid problems when using the YAML snippet and to improve the readability of the PHP code, the line indentations have been corrected.

[BUGFIX] Fix line indentations of YAML and PHP code snippets

---

Classes/Backend/FormEngine/SlugPrefix.php
Configuration/TCA/tx_news_domain_model_news.php
Documentation/Reference/TsConfig/General.rst

The prefix in the backend before the slug field can now be configured using tsconfig `tx_news.slugPrefix`.
Options:
- `none`: No prefix
- `default`: The domain just like before
- An integer: link to this page

[FEATURE] Configurable slug prefix in backend

---

Classes/Event/ModifyCacheTagsFromDemandEvent.php
Classes/Utility/Cache.php

By default the news extension sets `tx_news_pid_[pid]` cache tags based
on the storage pids configured in a news plugin.
This new event allows you to modify the list generated cache tags in
an event listener.
Use case example:
Imagine you have a single storage folder for news and you use
categories and tags to control which of your news appear where on the
website. Flushing all pages with plugins based on the storage page
whenever an article is edited is too much. Instead you want to set
cache tags based on categories an tags to flush only the pages
with matching plugins.

[FEATURE] Add PSR-14 event to modify cache tags based on demand

---

Classes/Controller/NewsController.php

When the title of a related news entry changes, you want the cache of the detail action flushed to display the updated title

[TASK] Set cache tags for related news in detail action

---

Classes/Hooks/DataHandlerHook.php
Classes/Hooks/FlexformHook.php
Configuration/Services.php
ext_localconf.php

Rename:
- Hooks/DataHandler -> Hooks/DataHandlerHook
- Hooks/BackendUtility -> Hooks/FlexformHook
This makes it easier using the classes of the core with the same name

[!!!][TASK] Rename 2 hooks to avoid same namings

---

Classes/ViewHelpers/ImageSizeViewHelper.php

To validate this patch: create an RSS feed of news according to the [manual](https://docs.typo3.org/p/georgringer/news/main/en-us/Tutorials/BestPractice/Rss/Index.html).
The only place where the `n:imageSize` viewhelper is used in combination with `property:'size'` is in `Resources/Private/Templates/News/List.xml`.
Expected behaviour after applying this patch: the `length` attribute in the RSS feed has a proper value instead of 0.

[BUGFIX] Proper check for valid URL path

---

Resources/Private/Language/locallang_be.xlf

I always stumble over these two fields in the plugin (I use the german translation). I usually just enter "today" and see what it does, then pick the desired one.  But it would be helpful also for editors to have a simpler wording.
If you agree on the simplified wording, I could also adapt it in german, but I haven't found ext_news on https://translation.typo3.org/de/ , where are the german translations (Oberes Zeiteinschränkung) stored?

Propose simplified wording for timeRestriction

---

Classes/Controller/NewsController.php

The $event->getAssignedValues()['news'] is now the basis for the creation of the paginator

[BUGFIX] Move pagination after event - fix paginator basis

---

Classes/Domain/Service/AbstractImportService.php

Just to be safe: All timestamp values less than 1 won't be converted to timestamp.

Do not convert empty timestamp to DateTime

---

ext_tables.php

According to the recommendation in https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Deprecation-82669-StreamlineBackendRoutePathInconsistencies.html the slash at the end of the route path should be removed.
In some installations, the slash means that the route cannot be resolved correctly resulting in an "Mixed Content" error in the browser because of a redirect of EXT:core/Resources/Public/JavaScript/Contrib/lit-html/lit-html.js to an "http://" URL without the slash. If you remove the slash in the module configuration, it works everywhere.
Currently the final URL looks like: https://domain.de/typo3/module/web/NewsAdministration/?token=... In contrast, the URL for the template module looks like this: https://domain.de/typo3/module/web/ts?token=... As you can see the core …

[BUGFIX] Use correct route for NewsAdministration module

---

Classes/Backend/FormEngine/SlugPrefix.php

Added a check to sys_language_uid to verify wether it is an array or an integer. This should prevent the TypeError issue when using SlugPrefix option. [#1886](https://github.com/georgringer/news/issues/1886)

[BUGFIX] Fix TypeError when using SlugPrefix option

---

README.md

And make clear it is not part of the main extension anymore

[Docs] promote news Administration by a link

---

.github/workflows/core11.yml
.github/workflows/core12.yml
Build/Scripts/runTests.sh

This pull-requests adds the unit test execution to the
GitHub Action testing matrix.
Additionally, this pull-request uses a more dynamic approach
for defining the docker-compose project name to avoid conflicts
on some systems with other runTests.sh powered repositories
like for example TYPO3 core mono repository.

[TASK] Enhance testing with runTests.sh and GitHub Action

---

Classes/Hooks/ItemsProcFunc.php

Due to the removal of switchingControllerActions it is currently not possible to order the list view by sorting field.
resolves #1964

[BUGFIX] Order news list by sorting is missing

---

Configuration/FlexForms/flexform_news.xml

To-top and to-bottom buttons will appear if field's size is greater or equal 5

#1969 Add top/bottom move buttons in plugin's flexform

---

Classes/Routing/NewsAliasMapper.php
Documentation/Tutorials/BestPractice/Routing/Index.rst
ext_localconf.php

Route Enhancer Configuration can be made easier for EXT:news.
This change adds a new Route Enhancer (NewsAliasMapper), which is a shorthand for the PersistedAliasMapper, it is registered with three custom types (news, categories + tags).
Before in your site configuration:
aspects:
news-title:
type: PersistedAliasMapper
tableName: tx_news_domain_model_news
routeFieldName: path_segment
type: NewsTitle
Now:
aspects:
news-title:
type: NewsTitle
The three new types are "NewsTitle" (for news records), "NewsTag" (for tag records) and "NewsCategory" (for sys_category records).
In addition, it supports the possibility that if no record (news, tag or category) was found, "0" is returned, thus having the News plugin to handle a invalid news identifier (e.g. a news which is now hidden).

[FEATURE] Introduce simplified AliasMapper for News Routing

---

.github/workflows/ci.yml
composer.json
ext_emconf.php

EXT:news claims to be compatible with TYPO3 v10, which is only partially true as PHP 7.4-specific features are used. The documentation confirms this on an [arbitrary page](https://docs.typo3.org/p/georgringer/news/10.0/en-us/Administration/Installation/Index.html).
Sadly, TYPO3 v10 is compatible with PHP 7.2, leading to exceptions due to said features being exclusive to PHP 7.4 and upwards. To circumvent exceptions and set the constraints in stone, the files `composer.json` and `ext_emconf.php` now explicitly set the PHP version constraint.

[BUGFIX] Add PHP version constraints

---

Configuration/TypoScript/setup.typoscript

This patch removes last occurrences of g+.
Fixes: #1975

[TASK] Remove superfluous TypoScript setting googlePlusLocale

---

Classes/Backend/FormEngine/SlugPrefix.php

New, not already saved records get a uid like "NEW56fe740dd5a455"; those records can not have a URL yet, and generateUrl() can not be called with (int) $recordId because in this initial case $recordId is a string.
Fixes: #1994

[BUGFIX] Check for valid recordId before generating URL

---

Build/testing-docker/docker-compose.yml
composer.json

`typo3/cms-extbase` requires `phpdocumentor/reflection-docblock`,
which includes a further dependency to `webmozart/assert`.
The indirect dependency "webmozart/assert" contained PHP 8.2
code emitting PHP native deprecation messages. That has been
fixed with ^1.11.0 of that package.
TYPO3 core has added a direct package version minimum constraint
as development package to the root composer.json file to mitigate
that dependency chain issue for PHP 8.2.
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75242
This change will add that packages as a direct development dependency
only, to ensure CI tests works properly with PHP8.2. It's not the job
of this extension to fix the indirect dependency constraint.
Used command(s):
```shell
composer req --dev --no-update \ …
```

[TASK] Ensure proper minimum indirect package version constraint

---

composer.json

Since TYPO3 core v12.0 `typo3/cms-composer-installers` in
version `5.0+` is a hard requirement. That package can only
be installed in version `3.x` and `4.0.0-RC1` for core v11.
With https://github.com/sbuerk/news/commit/97c530cff24371e #2005
the `typo3/cms-composer-installers` has been required with
`^3.1.3` only, which conflicts with TYPO3 core v12 constraint.
Due that conflict, composer install for v12 GitHub actions
has been falled back installing only TYPO3 core v11 instead.
During preparation to enable testing with PHP8.2, this popped
up because v12 executes Postgres tests. They are failing with
v11 and PHP8.2 until TYPO3 core patch for `doctrine/dbal` is
applied.
This change ensures, TYPO3 v12 can be installed by relaxing
the `typo3/cms-composer-installers` constraint allowing all …

[BUGFIX] Avoid dependency conflict with core requirements

---

Classes/Hooks/Labels.php

The category label hook might get called without a record during the cleanup and stops the execution of the cleanup command.
Fixes: #2009

[BUGFIX] prevent error in cleanup:deletedrecords command

---

Documentation/Tutorials/BestPractice/Routing/Index.rst

Hi There,
The DateMenu block above produces a 404 when used as is  - it seems that the "requirements" indentation is wrong. According to https://www.npostnik.de/typo3/404-fehlerseite-beim-routing-nach-update-auf-9-5-20/ - The "requirements block hast to be the same level as aspects and routes.
I fixed this in the above snippet.
Best regards, MT

Update "requirements" indentation for DateManu

---

Classes/Updates/PluginUpdater.php

The updater can not migrate to the new CTypes without a switchableControllerAction defined in the saved flexform.
Fixes: #2029

[BUGFIX] skip incomplete news plugins in plugin updater

---

Configuration/TypoScript/setup.typoscript

The order of the setting `plugin.tx_news.settings.detail.pageTitle.properties = title,teaser` seems to be not correct. Since the title is a mandatory field, there will never be the case that teaser appears in the title tag.
Correct should be with consideration of `alternativeTitle`.
`plugin.tx_news.settings.detail.pageTitle.properties = alternativeTitle,title`.
https://github.com/georgringer/news/issues/2028

The order of SEO page title

---

Documentation/Tutorials/ExtendNews/DataProcessing/LanguageMenuProcessor.rst

DisableLanguageMenuProcessor should only be processed if a news-record is given, else it is struggling with a wrong object for the route and end up in `Call to undefined method TYPO3\CMS\Core\Routing\SiteRouteResult::getRouteArguments()`. Another option would be inserting the snippet *only* on the detail page.

Use `if` with DisableLanguageMenuProcessor

---

Documentation/Tutorials/ExtendNews/ExtendFlexforms/Index.rst

The Hook mentioned in the current documentation was removed in TYPO3 v12. This PR updates the documentation to work in TYPO3 v12.

[DOC] Change FlexForm tutorial to work with TYPO3 v12

---

Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml
composer.json
ext_localconf.php

To make contribution and maintainance of configuration, scripts etc. for testing easier, we try to use a common standard across TYPO3 extensions.
The current standard for web-dir is .Build/Web and is used in the official example extensions (tea, docs-examples) as well as in most of the checked community extensions (in a subset of 20 of the most popular v12 extensions).
Related: TYPO3-Documentation/tea#802

[TASK] Use current standard for web-dir

---

Classes/DataProcessing/AddNewsToMenuProcessor.php
Classes/DataProcessing/DisableLanguageMenuProcessor.php

For more flexibility (and avoidance of overhead/errors), the `if` -roperty allows limiting DataProcessors to specific situations (e.g. the presence of a newId via `if.isTrue.data = GP:tx_news_pi1|news`).
Issue: #2074

[FEATURE] Support `if` in dataprocessors

---

Classes/Routing/AbstractNewsAliasMapper.php
Classes/Routing/NewsCategoryMapper.php
Classes/Routing/NewsTagMapper.php
Classes/Routing/NewsTitleMapper.php
ext_localconf.php

The original implementation reference the
'type' settings, which is never passed from Core.
Use dedicated classes to mitigate this shortcoming and have cleaner code.
Fixes #2045

[BUGFIX] Split NewsAliasMapper into dedicated classes

---

Build/Scripts/runTests.sh
Build/phpunit/UnitTestsBootstrap.php
Build/testing-docker/docker-compose.yml
composer.json

Ensure CI is working with newest core testing-framework,
which replaces the obsolete intermediate bridge plugin
to mitigate introduced behaviour changes by
"typo3/cms-composer-installers" 4RC1/5.
Tasks
* using tagged testing-framework
* adjust path settings
* removed obsolete bridge plugin
* use correct unit test bootstrap file
Used command(s):
```shell
composer remove --dev --no-update \
"sbuerk/typo3-cmscomposerinstallers-testingframework-bridge"
composer config --unset \
allow-plugins.sbuerk/typo3-cmscomposerinstallers-testingframework-bridge
composer require --dev --no-update \
"typo3/testing-framework":"^7.0.1"
```

[TASK] Ensure working `runTests.sh` and CI

---

ext_localconf.php

URLs for the single view usually have `action`, `controller` and `news` parameters. So we will need to include all of those into the list of canonicalized URL parameters in order to have proper canonical URLs even if the original URLs does not use the slug yet.

[BUGFIX] Create proper canonical URLs for the single view

---

Documentation/Tutorials/Templates/TemplateSelector/Index.rst

Currently only the `class` differs but the example should actually use the `List/Item` partial.

[DOCS] Load different partial in Template selector example

---

Classes/Hooks/PluginPreviewRenderer.php
Configuration/JavaScriptModules.php
Resources/Public/ESM/import.js
Resources/Public/ESM/page-layout.js

RequireJS has been deprecated in TYPO3 v12. [1]
Migrate existing backend javascript modules
to ECMAScript6 and configure a respective
import map. [2]
TYPO3 v11 compatibility is preserved by keep
using RequireJS.
[1] https://docs.typo3.org/c/typo3/cms-core/12.4/en-us/Changelog/12.0/Deprecation-97057-DeprecateRequireJSSupport.html
[2] https://docs.typo3.org/c/typo3/cms-core/12.4/en-us/Changelog/12.0/Feature-96510-InfrastructureForJavaScriptModulesAndImportmaps.html

[TASK] Add support for TYPO3 v12 ES6 modules

---

Classes/Controller/NewsController.php

Fixes is_array check warning:
```PHP Warning: Undefined array key "singleNews." in /var/www/html/public/typo3conf/ext/news/Classes/Controller/NewsController.php line 648```

[BUGFIX] fix undefined array key warning

---

Classes/Controller/NewsController.php

In case the overwriteDemand property 'category' is already an array this'll prevents an type error when calling trimExplode().
We're rendering the Category/List.html as a form with checkboxes:
```
<input type="checkbox" name="tx_news_pi1[overwriteDemand][categories][]" value="33">
<input type="checkbox" name="tx_news_pi1[overwriteDemand][categories][]" value="34">
<input type="checkbox" name="tx_news_pi1[overwriteDemand][categories][]" value="35">
```
This used to work with EXT:news 8.6 and got destroyed with a0b7f58f483968f90e7ffbd44dd6a36ad56f5be5 :joy: 
Fixes: #2195

[BUGFIX] Overwrite via tx_news_pi1[overwriteDemand][categories][] broken

---

Configuration/FlexForms/flexform_news_date_menu.xml

This is handled already in the code, only the flexform has been missing.

[BUGFIX] Allow orderDirection again for DateMenu plugin

---

Classes/Updates/PluginUpdater.php

The PluginUpdater uses the FlexFormTools to handle flexform migrations.
The core ext:form registers a hook for flexform processing, which expects `$GLOBALS['LANG']` to be present.

[BUGFIX] Ensure correct context for ext:form flexform hook

---

Classes/Updates/PluginUpdater.php

Ensure the plugins that need to be migrated are really news plugins, but not other CTypes that were a former plugin and reused.

[BUGFIX] Ensure only valid plugins are migrated in UpgradeWizard

---

Classes/Updates/PluginUpdater.php

As the LanguageService has own constructor arguments, the Factory needs to be used to create a valid LanguageService object.

[BUGFIX] Correctly create LanguageService in UpgradeWizard

---

Classes/Service/LinkHandlerTargetPageService.php

Add setter function to LinkHandlerTargetPageService called by ContentObjectRenderer->callUserFunction() to explicitly set an instance of the ContentObjectRenderer.
Fixes #2204

[BUGFIX] Add setter function

---

Tests/Unit/Backend/FormDataProvider/NewsRowInitializeNewTest.php

Also clean up another test and make the timing-related tests more strict.
Fixes #2130

[BUGFIX] Make a flaky test not timing-sensitive anymore

---

Build/testing-docker/docker-compose.yml
composer.json

For TYPO3 12, the minimum version should be the LTS release 12.4.0, not any lower version like 12.2 or 12.3.

[TASK] Only allow LTS core versions

---

Classes/Domain/Repository/AbstractDemandedRepository.php
Classes/Domain/Repository/CategoryRepository.php
Classes/Domain/Repository/TagRepository.php

The method execute() returns an array only if it is defined as a parameter. But this is not the case here, therefore only a QueryResultInterface<T> will be returned.

[TASK] Set correct return type

---

Classes/Domain/Model/News.php
Classes/Domain/Model/TtContent.php
Documentation/Tutorials/Templates/RenderContentElements/Index.rst

I haven’t removed the TypoScript snippet in the Docs and only pointed to a side effect. The problem is described in #2018.
Fixes #2018

[BUGFIX] Avoid nested content element get rendered twice

---

Documentation/Tutorials/BestPractice/Seo/Index.rst

Prevent the PHP error 'Unable to call method "getQueryParams" of non-object "request".' in contexts without a request object (i.e. CLI).
See matching pull request on TYPO3 core: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/pull/807

[DOC] Check request object in conditions #2251

---

Build/Scripts/runTests.sh

The previous default DB (SQLite) has some test failures, and we want the functional tests to run without failures with the default settings.

[TASK] Make MariaDB the default for functional tests in `runTests.sh`

---

Documentation/Tutorials/BestPractice/Routing/Index.rst

Order of the code in the yaml file is important on pages with plugin view "List and Detail".

[DOCS] Add tip for pagination routing

---

Documentation/Tutorials/BestPractice/Routing/Index.rst

This will probably sufficient for 90% of inexperienced users. And I always have to search for the quick basic configuration in small projects again

[DOCS] add a quick start section to the routing chapter

---

Classes/Backend/RecordList/RecordListConstraint.php
Classes/DataProcessing/AddNewsToMenuProcessor.php
Classes/Database/QueryGenerator.php
Classes/Domain/Repository/AdministrationRepository.php
Classes/Domain/Repository/CategoryRepository.php
Classes/Event/Listener/ModifyDatabaseQueryForContentEventListener.php
Classes/Event/Listener/ModifyDatabaseQueryForRecordListingEventListener.php
Classes/Hooks/Backend/PageViewQueryHook.php
Classes/Seo/NewsAvailability.php
Classes/Seo/NewsXmlSitemapDataProvider.php
Classes/Service/AccessControlService.php
Classes/Service/CategoryService.php
Classes/Service/LinkHandlerTargetPageService.php
Classes/Service/SlugService.php
Classes/Updates/PopulateCategorySlugs.php
Classes/Updates/PopulateTagSlugs.php
Classes/ViewHelpers/Category/CountViewHelper.php
Classes/ViewHelpers/SimplePrevNextViewHelper.php
Classes/ViewHelpers/Tag/CountViewHelper.php
Tests/Functional/ViewHelpers/SimplePrevNextViewHelperTest.php

In TYPO3 code, the TYPO3 `Connection` constants should be used instead.

[BUGFIX] Migrate usages of the PDO param type constants

---

composer.json

This should fix CS-Fixer on PHP 8.3 with lowest dependencies.

[BUGFIX] Bump the development dependencies

---

composer.json

We don't support Symfony 4.x anymore, and hence the listed Composer conflicts cannot happen anymore.

[TASK] Drop obsolete Composer conflicts

---

Classes/Domain/Repository/CategoryRepository.php
Classes/Domain/Repository/NewsRepository.php

`$importId` is declared as string everywhere. Except in `findOneByImportSourceAndImportId()` method signatures.

Set correct variable type of `$importId` in method signatures

---

Build/testing-docker/docker-compose.yml
composer.json

This is required for PHP 8.3 compatibility.

[BUGFIX] Raise the minimum 12LTS version

---

Classes/Domain/Model/News.php

in extbase models, you have to use the full namespace for properties. this fixes `Could not find class definition for name "GeorgRinger\News\Domain\Model\DateTime"` error
@see https://docs.typo3.org/typo3cms/exceptions/main/en-us/Exceptions/1476045117.html

[BUGFIX] Uncaught TYPO3 Exception: #1476045117

---

composer.json

Relying on transitional dependencies (and their version constraints) is considered bad practice.
Related to #2312

[BUGFIX] Make `symfony/console` an explicit dependency

---

Documentation/Reference/ViewHelpers/Index.rst
Documentation/Reference/ViewHelpers/RenderMediaViewHelper.rst

Add small documentation for the RenderMediaViewHelper to VieHelpers reference.

[DOCS] Add RenderMedia ViewHelper to docs

---

Classes/Controller/NewsController.php

The method initializeAction is not public api and protected in ActionController.
With this change I align the method visibility with the parent class.

[BUGFIX] Make inherited method visibility same as parent

---

Configuration/TCA/Overrides/z_misc_12_adoptions.php

The wrong source was used in the str_replace. This resulted in invalid value `1` for the eval field:
`GLOBALS['TCA'][$table]['columns'][$field]['config']['eval'] = 1`
Currently in 11.4.1 on TYPO3 12.4:
Expected result:

[BUGFIX] Use eval as source for eval

---

Documentation/Tutorials/BestPractice/ICalendar/Index.rst
Documentation/Tutorials/BestPractice/Rss/Index.rst
Documentation/Tutorials/BestPractice/Seo/Index.rst

With the introduction of the symfony expression language since TYPO3 9.4, the old syntax (such as the use of `globalVar`) is considered as deprecated. This patch converts all conditions to the new syntax.
A [null-safe operator in the TypoScript conditions](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.1/Feature-100586-Null-safeOperatorInTypoScriptConditions.html#feature-100586-null-safe-operator-in-typoscript-conditions) was deliberately not used in this patch, as this was only introduced from TYPO3 v12.1 onwards. As soon as support for v11 is ended, this more elegant abbreviation `[getTSFE()?.type == 9819]` can be used accordingly.
In addition, `[global]` is replaced by the more suitable variant `[END]`, which only terminates the previous condition.
Related: #2458

[DOCS] Modernize outdated conditions still using globalVar

---

Documentation/Tutorials/BestPractice/Linkhandler/Index.rst

With using the (old) `TYPO3\CMS\Recordlist\LinkHandler\RecordLinkHandler` selecting news in sys_redirects isn't possible.

Docs mention wrong linkHandler

---

Classes/Hooks/PluginPreviewRenderer.php

This was introduced 2 weeks ago in https://review.typo3.org/c/Packages/TYPO3.CMS/+/83900
It blocks applying the latest TYPO3 security update v12.4.15
Fixes: #2476

[BUGFIX] 5th argument BU::wrapClickMenuOnIcon() must be an array

---

Classes/Controller/CategoryController.php
Classes/Controller/NewsController.php
Classes/Controller/TagController.php
Classes/Domain/Model/Dto/NewsDemand.php
Classes/Seo/NewsXmlSitemapDataProvider.php
Classes/Utility/ClassCacheManager.php
Classes/Utility/ClassLoader.php

With PHP 8.4 marking method parameter implicitly nullable
is deprecated and will emit a `E_DEPRECATED` warning. One
recommended way to resolve this, is making it explicitly
nullable using the `?` nullable operator or adding a null
type to an union type definition. [[1]](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated)
This prepares the way towards PHP 8.4 compatibility.
* [[1] https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated)

[TASK] Avoid implicitly nullable class method parameter

---

ext_localconf.php

AltPageTitleProvider has been removed in TYPO3 10, see: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Breaking-87193-DeprecatedFunctionalityRemoved.html

[TASK] Remove reference to AltPageTitleProvider from config

---

Configuration/FlexForms/flexform_category_list.xml
Configuration/FlexForms/flexform_news.xml
Configuration/FlexForms/flexform_news_date_menu.xml
Configuration/FlexForms/flexform_news_detail.xml
Configuration/FlexForms/flexform_news_list.xml
Configuration/FlexForms/flexform_news_search_form.xml
Configuration/FlexForms/flexform_news_selected_list.xml
Configuration/FlexForms/flexform_tag_list.xml

When using the new record transformation processor in TYPO3 v13, FlexForm is also transformed and has its relations resolved. In order to have desired cardinality, the new option `relationship` has to be defined. For fields with maxitems set to 1, the desired cardinality is most likely `manyToOne`.
Fixes: #2539

[TASK] Add relationship `manyToOne` for group fields with maxitems 1

---

Classes/Controller/NewsController.php
Classes/Utility/Cache.php

$GLOBALS['TSFE']->addCacheTags is deprecated and needs to be managed for TYPO3 13.
Resolves: #2530

[BUGFIX] Handle deprecated cache tag management

---

Classes/DataProcessing/AddNewsToMenuProcessor.php
Classes/DataProcessing/DisableLanguageMenuProcessor.php
Configuration/Services.yaml
Documentation/Tutorials/BestPractice/BreadcrumbMenu.rst
Documentation/Tutorials/BestPractice/Seo/Index.rst
Documentation/Tutorials/ExtendNews/DataProcessing/AddNewsToMenuProcessor.rst
Documentation/Tutorials/ExtendNews/DataProcessing/LanguageMenuProcessor.rst

All data processors were tagged according to [Feature: #96005](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.1/Feature-96005-AllowTaggingandAliasingOfDataProcessors.html) and given an alias. In addition, all occurrences of core data processors in the documentation were used with the corresponding aliases.

[FEATURE] Tag and alias for data processors

---

Configuration/Backend/Modules.php
Configuration/Icons.php

`icon` is deprecated for module registration.
This PR is registering the icon `module_administration.svg` with Icon API and using it as `iconIdentifier` in `Modules.php`

[TASK] Use iconIdentifier in module registration

---

Resources/Private/Templates/Styles/Twb5/Templates/Category/List.html

[BUGFIX] Use the free version class of the Font Awesome minus/plus icon.
Fix the minus/plus icon next to the categories not rendering when using the free version of Font Awesome.
Without this fix, the minus icon cannot render if you are using the free version of Font Awesome
This replaces the class of the minus/plus icon for the one available in the free version.
solid version (free):
https://fontawesome.com/v5/icons/minus?f=classic&s=solid
regular version (pro):
https://fontawesome.com/v5/icons/minus?f=classic&s=regular
Resolves: #2591

Change the minus/plus pro FA icon class to the free icon class

---

README.md

TYPO3 11 is not supported anymore in main branch. It can therefor be removed from the badges.

[DOCS] Remove TYPO3 11 compatibility of main branch

---

Configuration/TCA/Overrides/tt_content.php

solves #2607
Ensure that the crdate and tstamp fields in the tt_content table are displayed as datetime fields. 
Also, retain their original labels.

[BUGFIX] Retain datetime and labels for tt_content crdate and tstamp fields

---

Classes/Seo/NewsXmlSitemapDataProvider.php
Configuration/TypoScript/SeoSitemap/setup.typoscript
Documentation/Tutorials/BestPractice/Seo/Index.rst

It's currently not possible to determine the order for the news they be displayed in the Seo Sitemap. Ascending or descending. This PR adds another TypoScript configuration for this.
Related: #2618

[TASK] Add config to sort news in seo sitemap

---

Classes/ViewHelpers/SimplePrevNextViewHelper.php

When using the ViewHelper on a non-default language page it tries to invoke a now recently protected function.
Call to protected method TYPO3\CMS\Core\Domain\Repository\PageRepository::getRecordOverlay() from scope GeorgRinger\News\ViewHelpers\SimplePrevNextViewHelper
Migration according to TYPO3 Changelog Breaking: #98303
Resolves: #2596

[BUGFIX] Migrate getRecordOverlay to getLanguageOverlay in SimplePrevNextViewHelper (#2596)

---

Classes/Domain/Service/AbstractImportService.php

Fix #2652 - Prevent uncaught TYPO3 exceptions for typed property exceptions

---

Classes/ViewHelpers/ImageSizeViewHelper.php

Fixes a PHP 8.1+ deprecation warning in ImageSizeViewHelper where null could be passed to trim(), which expects a string.
The 'image' argument is now explicitly cast to string using (string)($arguments['image'] ?? '') to ensure compatibility with newer PHP versions and avoid future fatal errors.
No changes in functionality—this is a safe internal fix.

fix(viewhelper): prevent deprecation warning from null passed to trim()

---

ext_tables.php

This removes the trailing slash in the backend administration module.
For me it seems unconventional to set it (at least i found no other modules with trailing slash in a quick search)
And it leads to a funny error when trailing slashes are automatically removed by `.htaccess`: Because that htaccess rule redirects basically to an undefined backend route (without slash) which, because its undefined, then redirects to `/typo3/login`, which redirects to main backend entry because we are already logged in. That causes this screen: 
I totally see that this is a edge case, but i think that slash is there by accident (it came in https://github.com/georgringer/news/commit/2f8c4b03e39e307c6a1c173ecbd420689f05dad0 and was without slash before) and that there is nothing wrong about changing it back …

[BUGFIX] Removes trailing slash in backend module
